//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.algonquincollege.com/cst8259/labs")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "https://www.algonquincollege.com/cst8259/labs", IsNullable = false)]
public partial class ships
{

    private shipsShip[] shipField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ship")]
    public shipsShip[] ship
    {
        get
        {
            return this.shipField;
        }
        set
        {
            this.shipField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.algonquincollege.com/cst8259/labs")]
public partial class shipsShip
{

    private string nameField;

    private uint imoField;

    private ShipType typeField;

    private string flagField;

    private uint gross_tonField;

    private uint dwtField;

    private ushort lengthField;

    private byte beamField;

    private decimal draughtField;

    private string photoField;

    private ushort build_yearField;

    private string ownerField;

    private string managerField;

    private shipsShipLocation locationField;

    private string destinationField;

    private string last_portField;

    private string eTAField;

    private shipsShipShip_evaluation ship_evaluationField;

    private string last_updateField;

    /// <remarks/>
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    public uint imo
    {
        get
        {
            return this.imoField;
        }
        set
        {
            this.imoField = value;
        }
    }

    /// <remarks/>
    public ShipType type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    public string flag
    {
        get
        {
            return this.flagField;
        }
        set
        {
            this.flagField = value;
        }
    }

    /// <remarks/>
    public uint gross_ton
    {
        get
        {
            return this.gross_tonField;
        }
        set
        {
            this.gross_tonField = value;
        }
    }

    /// <remarks/>
    public uint dwt
    {
        get
        {
            return this.dwtField;
        }
        set
        {
            this.dwtField = value;
        }
    }

    /// <remarks/>
    public ushort length
    {
        get
        {
            return this.lengthField;
        }
        set
        {
            this.lengthField = value;
        }
    }

    /// <remarks/>
    public byte beam
    {
        get
        {
            return this.beamField;
        }
        set
        {
            this.beamField = value;
        }
    }

    /// <remarks/>
    public decimal draught
    {
        get
        {
            return this.draughtField;
        }
        set
        {
            this.draughtField = value;
        }
    }

    /// <remarks/>
    public string photo
    {
        get
        {
            return this.photoField;
        }
        set
        {
            this.photoField = value;
        }
    }

    /// <remarks/>
    public ushort build_year
    {
        get
        {
            return this.build_yearField;
        }
        set
        {
            this.build_yearField = value;
        }
    }

    /// <remarks/>
    public string owner
    {
        get
        {
            return this.ownerField;
        }
        set
        {
            this.ownerField = value;
        }
    }

    /// <remarks/>
    public string manager
    {
        get
        {
            return this.managerField;
        }
        set
        {
            this.managerField = value;
        }
    }

    /// <remarks/>
    public shipsShipLocation location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }

    /// <remarks/>
    public string destination
    {
        get
        {
            return this.destinationField;
        }
        set
        {
            this.destinationField = value;
        }
    }

    /// <remarks/>
    public string last_port
    {
        get
        {
            return this.last_portField;
        }
        set
        {
            this.last_portField = value;
        }
    }

    /// <remarks/>
    public string ETA
    {
        get
        {
            return this.eTAField;
        }
        set
        {
            this.eTAField = value;
        }
    }

    /// <remarks/>
    public shipsShipShip_evaluation ship_evaluation
    {
        get
        {
            return this.ship_evaluationField;
        }
        set
        {
            this.ship_evaluationField = value;
        }
    }

    /// <remarks/>
    public string last_update
    {
        get
        {
            return this.last_updateField;
        }
        set
        {
            this.last_updateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.algonquincollege.com/cst8259/labs")]
public enum ShipType
{

    /// <remarks/>
    Container,

    /// <remarks/>
    Bulker,

    /// <remarks/>
    Tanker,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("LNG Tanker")]
    LNGTanker,

    /// <remarks/>
    PCC,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("General Cargo")]
    GeneralCargo,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.algonquincollege.com/cst8259/labs")]
public partial class shipsShipLocation
{

    private decimal longitudeField;

    private decimal latitudeField;

    /// <remarks/>
    public decimal longitude
    {
        get
        {
            return this.longitudeField;
        }
        set
        {
            this.longitudeField = value;
        }
    }

    /// <remarks/>
    public decimal latitude
    {
        get
        {
            return this.latitudeField;
        }
        set
        {
            this.latitudeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://www.algonquincollege.com/cst8259/labs")]
public partial class RangeType
{

    private byte minField;

    private byte maxField;

    private byte valueField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte min
    {
        get
        {
            return this.minField;
        }
        set
        {
            this.minField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public byte max
    {
        get
        {
            return this.maxField;
        }
        set
        {
            this.maxField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public byte Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "https://www.algonquincollege.com/cst8259/labs")]
public partial class shipsShipShip_evaluation
{

    private RangeType vessel_qualityField;

    private RangeType crew_performanceField;

    private RangeType crew_attitudeField;

    private RangeType fuel_efficiencyField;

    private RangeType safety_score_by_third_partyField;

    /// <remarks/>
    public RangeType vessel_quality
    {
        get
        {
            return this.vessel_qualityField;
        }
        set
        {
            this.vessel_qualityField = value;
        }
    }

    /// <remarks/>
    public RangeType crew_performance
    {
        get
        {
            return this.crew_performanceField;
        }
        set
        {
            this.crew_performanceField = value;
        }
    }

    /// <remarks/>
    public RangeType crew_attitude
    {
        get
        {
            return this.crew_attitudeField;
        }
        set
        {
            this.crew_attitudeField = value;
        }
    }

    /// <remarks/>
    public RangeType fuel_efficiency
    {
        get
        {
            return this.fuel_efficiencyField;
        }
        set
        {
            this.fuel_efficiencyField = value;
        }
    }

    /// <remarks/>
    public RangeType safety_score_by_third_party
    {
        get
        {
            return this.safety_score_by_third_partyField;
        }
        set
        {
            this.safety_score_by_third_partyField = value;
        }
    }
}
